programs:
  my_ping:
    cmd: "ping google.com"
    numprocs: 1
    autostart: true
    status: true
    error_code: 4
    restart: Always
    min_runtime: 1
    max_relaunch_retry: 3
    signal_stopper: SIGKILL